/**
 * Superadmin KB Export API
 *
 * GET /api/superadmin/kb/export?questionnaire_id=xxx&org_id=xxx
 *
 * Returns the full locked KB as a single markdown document.
 * Only works on locked questionnaires.
 */

import { NextRequest, NextResponse } from 'next/server'
import { getSuperadmin } from '@/lib/superadmin-middleware'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export async function GET(request: NextRequest) {
    const admin = await getSuperadmin(request)
    if (!admin) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const orgId = request.nextUrl.searchParams.get('org_id')
    const qrId = request.nextUrl.searchParams.get('questionnaire_id')

    if (!orgId || !qrId) {
        return NextResponse.json({ error: 'org_id and questionnaire_id required' }, { status: 400 })
    }

    // Load questionnaire
    const { data: qr } = await supabase
        .from('kb_questionnaire_responses')
        .select('company_name, status, locked_at')
        .eq('id', qrId)
        .eq('org_id', orgId)
        .single()

    if (!qr) return NextResponse.json({ error: 'Not found' }, { status: 404 })

    // Load sections ordered
    const { data: sections } = await supabase
        .from('kb_master_sections')
        .select('section_number, section_title, content, status')
        .eq('questionnaire_id', qrId)
        .eq('org_id', orgId)
        .order('section_number', { ascending: true })

    if (!sections || sections.length === 0) {
        return NextResponse.json({ error: 'No sections found' }, { status: 404 })
    }

    // Build markdown document
    const company = qr.company_name || 'Organization'
    const date = qr.locked_at ? new Date(qr.locked_at).toLocaleDateString() : new Date().toLocaleDateString()
    const status = qr.status

    let md = `# ${company} — Knowledge Base\n\n`
    md += `> Generated by Axiom · Status: ${status} · ${date}\n\n`
    md += `---\n\n`

    for (const s of sections) {
        md += `## Section ${s.section_number}: ${s.section_title}\n\n`
        if (s.content && s.content.trim()) {
            md += `${s.content.trim()}\n\n`
        } else {
            md += `*No content generated for this section.*\n\n`
        }
        md += `---\n\n`
    }

    // Return as downloadable markdown file
    const filename = `${company.replace(/[^a-zA-Z0-9]/g, '_')}_KB_${date.replace(/\//g, '-')}.md`

    return new NextResponse(md, {
        headers: {
            'Content-Type': 'text/markdown; charset=utf-8',
            'Content-Disposition': `attachment; filename="${filename}"`,
        },
    })
}
