/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ['selector', '[data-theme$="-night"]'],
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                primary: 'var(--color-primary)',
                'primary-hover': 'var(--color-primary-hover)',
                secondary: 'var(--color-secondary)',
                accent: 'var(--color-accent)',
                'accent-hover': 'var(--color-accent-hover)',
                background: 'var(--color-background)',
                surface: 'var(--color-surface)',
                surfaceHover: 'var(--color-surface-hover)',
                surfaceElevated: 'var(--color-surface-elevated)',
                textPrimary: 'var(--color-text-primary)',
                textSecondary: 'var(--color-text-secondary)',
                textTertiary: 'var(--color-text-tertiary)',
                textInverse: 'var(--color-text-inverse)',
                border: 'var(--color-border)',
                borderHover: 'var(--color-border-hover)',
                borderFocus: 'var(--color-border-focus)',
                overlay: 'var(--color-overlay)',
                shadow: 'var(--color-shadow)',
                success: 'var(--color-success)',
                'success-muted': 'var(--color-success-muted)',
                warning: 'var(--color-warning)',
                'warning-muted': 'var(--color-warning-muted)',
                error: 'var(--color-error)',
                'error-muted': 'var(--color-error-muted)',
                info: 'var(--color-info)',
                'info-muted': 'var(--color-info-muted)',
                glow: 'var(--color-glow)',
            },
            spacing: {
                xs: 'var(--spacing-xs)',
                sm: 'var(--spacing-sm)',
                md: 'var(--spacing-md)',
                lg: 'var(--spacing-lg)',
                xl: 'var(--spacing-xl)',
                '2xl': 'var(--spacing-2xl)',
            },
            fontFamily: {
                sans: 'var(--font-sans)',
                mono: 'var(--font-mono)',
                display: 'var(--font-display)',
            },
            fontSize: {
                xs: 'var(--text-xs)',
                sm: 'var(--text-sm)',
                base: 'var(--text-base)',
                lg: 'var(--text-lg)',
                xl: 'var(--text-xl)',
                '2xl': 'var(--text-2xl)',
                '3xl': 'var(--text-3xl)',
                '4xl': 'var(--text-4xl)',
            },
            borderRadius: {
                sm: 'var(--radius-sm)',
                md: 'var(--radius-md)',
                lg: 'var(--radius-lg)',
                xl: 'var(--radius-xl)',
                full: 'var(--radius-full)',
            },
            boxShadow: {
                sm: 'var(--shadow-sm)',
                md: 'var(--shadow-md)',
                lg: 'var(--shadow-lg)',
                xl: 'var(--shadow-xl)',
                glow: 'var(--shadow-glow)',
                'glow-lg': 'var(--shadow-glow-lg)',
            },
            transitionDuration: {
                fast: 'var(--duration-fast)',
                normal: 'var(--duration-normal)',
                slow: 'var(--duration-slow)',
            },
            transitionTimingFunction: {
                theme: 'var(--easing)',
                smooth: 'var(--easing-smooth)',
                bounce: 'var(--easing-bounce)',
            },
        },
    },
    plugins: [],
}
