import { Phase } from './data'

export const PHASES_5_9: Phase[] = [
    {
        num: 5, title: 'Pre-Launch Validation', subtitle: 'Hard Authorization Gate',
        color: '#ef4444', engine: 'Cross-engine', owner: 'Delivery + MarketWriter (joint)',
        objective: 'Validate system integrity under simulated conditions. Binary gate: Launch Authorized or Launch Blocked.',
        steps: ['Start validation run', 'Run delivery test', 'Run reply reception test', 'Run reply timing test', 'Run routing test', 'Run opt-out detection test', 'Run suppression enforcement test', 'Run bounce handling test', 'Run edge-case / hostile test', 'Run thread continuity test', 'Aggregate results', 'Authorize or block launch'],
        outputs: ['Validated system', 'Verified routing', 'Verified suppression', 'Verified reply path', 'Launch authorization decision'],
        entryCondition: 'Phase 4 complete',
        exitConditions: ['Validation run executed', 'All test types executed', 'No critical failures', 'Routing verified', 'Suppression verified', 'Reply path verified', 'System stable'],
        failureConditions: ['Delivery failure', 'Reply failure', 'Opt-out failure', 'Suppression failure', 'Routing instability', 'Thread mismatch'],
        gates: ['Validation run executed', 'All test types executed', 'No critical failures', 'Routing verified', 'Suppression verified', 'Reply path verified', 'System stable'],
        systemLaws: ['No launch without passing Pre-Launch Validation', 'No override of suppression or compliance rules'],
        modules: ['Validation Workspace', 'QA and Routing', 'Test Sends and Replies'],
    },
    {
        num: 6, title: 'Controlled Launch', subtitle: 'Initial Live Signal Capture',
        color: '#22c55e', engine: 'Delivery Engine', owner: 'Delivery Engine',
        objective: 'Begin live execution under strict control. Objective is generating first trustworthy signal set without corrupting the system.',
        steps: ['Start controlled launch', 'Assign low initial send volume', 'Distribute across mailboxes', 'Execute sends', 'Capture early signal', 'Evaluate signal quality', 'Evaluate system health', 'Evaluate partner handling', 'Decide scale eligibility', 'Hold, reduce, or approve scale'],
        outputs: ['Initial live signal', 'Validated system behavior', 'Scale eligibility decision', 'Protected delivery state'],
        entryCondition: 'Phase 5 passed',
        exitConditions: ['Initial signal collected', 'Signal usable', 'Delivery health stable', 'System behavior verified', 'Partner handling confirmed'],
        failureConditions: ['Scaling too early', 'Signal ignored', 'Partner failure to follow up', 'ICP drift'],
        gates: ['Usable or strong signal', 'Healthy delivery state', 'Stable system behavior', 'Partner handling confirmed'],
        systemLaws: ['No scale without validated signal quality', 'No optimization on invalid signals'],
        modules: ['Launch Workspace', 'Test Sends and Replies', 'Delivery Engine Workspace'],
    },
    {
        num: 7, title: 'Learning & Optimization', subtitle: 'Governed Learning',
        color: '#a855f7', engine: 'Cross-engine', owner: 'MarketWriter (primary)',
        objective: 'Convert live execution signal into governed decisions, system improvements, and durable knowledge.',
        steps: ['Validate signal integrity', 'Segment signal by layer', 'Interpret signal', 'Generate candidate decisions', 'Validate against system law', 'Approve changes', 'Write learning to local KB', 'Promote to candidate-global if warranted', 'Apply controlled rule updates'],
        outputs: ['Validated insights', 'System improvements', 'Updated local knowledge', 'Candidate-global patterns', 'Refined execution rules'],
        entryCondition: 'Phase 6 active with usable signal',
        exitConditions: ['Continuous — does not end'],
        failureConditions: ['Overreacting to small data', 'Mixing multiple variables', 'Promoting weak insights', 'Skipping writeback discipline'],
        gates: [],
        systemLaws: ['No optimization on invalid signals', 'No mixing of beliefs within a sequence'],
        modules: ['Learning Workspace', 'Reporting Workspace'],
    },
    {
        num: 8, title: 'Reporting & Partner Mgmt', subtitle: 'Decision Infrastructure',
        color: '#ec4899', engine: 'Governance', owner: 'Success / Strategy',
        objective: 'Convert execution and learning outputs into aligned decisions, partner coordination, and system accountability.',
        steps: ['Collect metrics', 'Validate metrics', 'Analyze by layer', 'Identify issues', 'Capture partner feedback', 'Generate decisions', 'Log decisions', 'Communicate with partner', 'Track issues to resolution'],
        outputs: ['Aligned partner', 'Tracked decisions', 'Validated reporting', 'Closed feedback loop', 'Controlled system evolution'],
        entryCondition: 'Phase 6 and Phase 7 active',
        exitConditions: ['Continuous — dashboards active, reports generated, decisions logged'],
        failureConditions: ['Vanity reporting', 'No feedback loop', 'No decision tracking', 'Misattributing issues'],
        gates: [],
        systemLaws: ['No downstream conclusions without upstream health validation'],
        modules: ['Reporting Workspace', 'Launch Workspace', 'Learning Workspace'],
    },
    {
        num: 9, title: 'De-Activation & Handover', subtitle: 'Offboarding',
        color: '#78716c', engine: 'Governance', owner: 'Commercial / Strategy',
        objective: 'Orderly termination of the rev-share partnership and disposition of Sovereign Memory.',
        steps: ['Infrastructure reclamation', 'State locking to terminal', 'Data re-translation export', 'IP boundary enforcement', 'Final audit export generation'],
        outputs: ['Reclaimed infrastructure', 'Locked terminal state', 'Partner data export', 'Master system log'],
        entryCondition: 'Partnership termination triggered',
        exitConditions: ['All assets reclaimed', 'State locked', 'Data exported', 'Audit complete'],
        failureConditions: ['Data leakage', 'Incomplete reclamation', 'Missing audit trail'],
        gates: [],
        systemLaws: [],
        modules: [],
    },
]
