export const NODE_DETAILS: Record<string, { title: string; icon: string; color: string; desc: string; bullets: string[]; route?: string }> = {
    refinery: { title: 'Refinery Nexus', icon: '🏭', color: '#10b981', desc: 'Lead ingestion and verification engine.', bullets: ['S3/CSV upload → ClickHouse ingestion', '9-check email verification pipeline', 'Quality segmentation: Gold → Silver → Bronze → Quarantine', 'Only Gold-tier leads flow to Axiom KB'], route: undefined },
    kb: { title: 'Knowledge Base', icon: '📚', color: '#a78bfa', desc: 'Org-scoped document store with vector embeddings.', bullets: ['Brand guides, ICP docs, offer specs uploaded by client', 'Chunked + embedded for RAG retrieval', 'Version-tracked with stage management', 'Agents query via cosine similarity search'], route: '/kb-manager' },
    brain: { title: 'The Brain', icon: '🧠', color: '#8b5cf6', desc: 'Org-wide intelligence layer — the canonical source of truth.', bullets: ['Persona + guardrails inherited by all agents', 'brain_memories: learned insights from campaign data', 'brain_reflections: periodic performance summaries', 'brain_learning_events: full audit trail'], route: '/superadmin/brains' },
    prompts: { title: 'Prompt Studio', icon: '✨', color: '#f59e0b', desc: 'Versioned prompt blocks assigned to brains and agents.', bullets: ['Categories: foundation, persona, instruction, guardrails, domain, task', 'Assigned via prompt_assignments (polymorphic)', 'Priority ordering within each category', '15 production seed prompts across 5 agent types'], route: '/superadmin/prompt-library' },
    agents: { title: 'Agent Swarm', icon: '🤖', color: '#60a5fa', desc: 'Specialized AI executors with role-based capabilities.', bullets: ['5 roles: writer, analyst, content, coach, generalist', 'Each agent: LLM config + tools + RAG + memory', '3-layer: agent_templates → brain_agents → org_agents', 'Decision audit trail in agent_decision_log'], route: '/superadmin/agents' },
    workflow: { title: 'Workflow Engine', icon: '⚙️', color: '#14b8a6', desc: 'Visual node-based pipeline builder with 36+ node types.', bullets: ['Drag-and-drop ReactFlow canvas', 'Agent nodes auto-load brain context + prompt blocks', 'Logic: conditionals, loops, delays, transforms', 'Triggers: manual, scheduled (cron), webhook, signal'], route: '/superadmin/workflow-manager' },
    content: { title: 'Generated Content', icon: '📝', color: '#ec4899', desc: 'AI-produced emails, landing pages, and research dossiers.', bullets: ['Email Writer: subject + body with AIDA/PAS/BAB', 'Page Builder: mobile-first HTML, WCAG 2.1 AA', 'Each output logs: tokens, cost, model, duration', 'Human-in-loop approval nodes available'], route: undefined },
    mailwizz: { title: 'MailWizz Satellites', icon: '📧', color: '#ef4444', desc: '5-server SMTP swarm with dedicated IPs and domains.', bullets: ['5 SMTP servers, 5 TLDs, 5 dedicated IPs', '50 sending identities (10 per server)', 'Warmup pacing: 50 → 200 → 1K → 3K/day per server', 'Domain rotation for reputation isolation'], route: '/superadmin/email-providers' },
    signals: { title: 'Signal Events', icon: '📊', color: '#f43f5e', desc: 'Raw webhook data from MailWizz campaigns.', bullets: ['Events: open, click, reply, bounce, complaint, unsub', 'Tagged with partner_id, belief_id, flow_id, step_id', 'Aggregated into belief_daily_rollup + partner_daily_rollup', 'GENERATED ALWAYS columns for computed rates'], route: '/superadmin/belief-dashboard' },
    coach: { title: 'Marketing Coach', icon: '🎓', color: '#6366f1', desc: 'Analytical agent that interprets data and updates Brain.', bullets: ['Queries daily rollups, identifies trends', 'Compares angle performance by ICP segment', 'Writes brain_memories with confidence scores', 'Auto-pauses beliefs exceeding bounce/complaint thresholds'], route: '/superadmin/mastery-agents' },
}
