-- SEED: Email Writer — Instruction + Guardrails
INSERT INTO prompt_blocks (slug, name, description, category, content, tags, is_system, is_active, variables) VALUES
('email-writer-instruction', 'Email Writer — Instruction', 'Step-by-step cold email structure', 'instruction',
E'Email Structure (Cold Outreach):\n\n1. SUBJECT LINE (3-7 words)\n   - Lowercase except proper nouns\n   - NO emoji, NO punctuation tricks\n   - Reference something specific: their company, role, or industry\n   - Examples: "{{company_name}}''s Q2 gap", "quick thought on {{pain_point}}"\n\n2. OPENING LINE (personalized hook)\n   - Reference something real: recent news, LinkedIn post, company milestone\n   - NO "I hope this finds you well" or "My name is..."\n   - Pattern: [Observation about them] → [Bridge to relevance]\n\n3. PAIN / PROBLEM (1-2 sentences)\n   - Name the specific pain they feel in their role\n   - Use their language, not marketing speak\n   - Pattern: "Most {{role}} teams struggle with [specific problem] because [root cause]"\n\n4. VALUE / SOLUTION (1-2 sentences)\n   - What changes when they solve this\n   - Include ONE proof point (client result, metric, case study)\n   - Pattern: "We helped [similar company] [specific result] in [timeframe]"\n\n5. CTA (soft ask)\n   - Low friction: question, not demand\n   - Pattern: "Worth a 15-min call to see if this applies to {{company_name}}?"\n   - NEVER: "Book a demo", "Schedule a call", "Let me know when you''re free"',
ARRAY['email','writer','instruction','cold-outreach','structure'], true, true,
'[{"name":"company_name","description":"Target company","required":false,"default":""},{"name":"pain_point","description":"Main pain point","required":false,"default":""},{"name":"role","description":"Target role/title","required":false,"default":""}]'::jsonb),

('email-writer-guardrails', 'Email Writer — Guardrails', 'Compliance, deliverability, and anti-patterns', 'guardrails',
E'NEVER DO:\n- Use ALL CAPS for emphasis\n- Include attachment language ("see attached", "I''ve attached")\n- Use spam triggers: "act now", "limited time", "guaranteed", "free", "click here"\n- Make unsubstantiated claims about results\n- Use more than one exclamation mark per email\n- Write emails longer than 200 words\n- Include more than one link\n- Use generic greetings ("Dear Sir/Madam", "To whom it may concern")\n- Begin with "I" as the first word\n- Use jargon the recipient wouldn''t know\n- Reference buying or purchasing in cold outreach\n- Use countdown urgency ("only 3 spots left")\n- Use link shorteners (bit.ly, tinyurl)\n\nCOMPLIANCE (CAN-SPAM):\n- Physical mailing address required\n- Unsubscribe mechanism required\n- Identify as advertisement when applicable\n- Accurate "From" headers\n- Honor opt-outs within 10 business days\n\nDELIVERABILITY:\n- Minimal or zero images in cold outreach\n- Plain text or minimal HTML\n- Limit to 1 link maximum\n- Avoid red-flag words: "urgent", "winner", "congratulations", "cash"',
ARRAY['email','writer','guardrails','compliance','deliverability'], true, true, '[]'::jsonb);
